/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentExecutionGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "POLICY_REGISTRY"
      | "REGISTRY"
      | "classifyCalldata"
      | "dailySpend"
      | "eip712Domain"
      | "execute"
      | "executeWithApproval"
      | "hashApproval"
      | "hashIntent"
      | "nextNonce"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EIP712DomainChanged" | "IntentExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "POLICY_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "REGISTRY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "classifyCalldata",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailySpend",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithApproval",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashApproval",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashIntent",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nextNonce",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "POLICY_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "REGISTRY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "classifyCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailySpend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeWithApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hashIntent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextNonce", data: BytesLike): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentExecutedEvent {
  export type InputTuple = [
    agent: AddressLike,
    wallet: AddressLike,
    target: AddressLike,
    nonce: BigNumberish,
    policyHash: BytesLike
  ];
  export type OutputTuple = [
    agent: string,
    wallet: string,
    target: string,
    nonce: bigint,
    policyHash: string
  ];
  export interface OutputObject {
    agent: string;
    wallet: string;
    target: string;
    nonce: bigint;
    policyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentExecutionGuard extends BaseContract {
  connect(runner?: ContractRunner | null): AgentExecutionGuard;
  waitForDeployment(): Promise<this>;

  interface: AgentExecutionGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  POLICY_REGISTRY: TypedContractMethod<[], [string], "view">;

  REGISTRY: TypedContractMethod<[], [string], "view">;

  classifyCalldata: TypedContractMethod<
    [data: BytesLike],
    [[bigint, string] & { selector: string }],
    "view"
  >;

  dailySpend: TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint] & { day: bigint; spent: bigint }],
    "view"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  execute: TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike,
      signature: BytesLike
    ],
    [string],
    "payable"
  >;

  executeWithApproval: TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike,
      signature: BytesLike,
      approvalDeadline: BigNumberish,
      approvalSignature: BytesLike
    ],
    [string],
    "payable"
  >;

  hashApproval: TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      calldataHash: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike,
      approvalDeadline: BigNumberish
    ],
    [string],
    "view"
  >;

  hashIntent: TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      calldataHash: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike
    ],
    [string],
    "view"
  >;

  nextNonce: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "POLICY_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "classifyCalldata"
  ): TypedContractMethod<
    [data: BytesLike],
    [[bigint, string] & { selector: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "dailySpend"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint] & { day: bigint; spent: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike,
      signature: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeWithApproval"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike,
      signature: BytesLike,
      approvalDeadline: BigNumberish,
      approvalSignature: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "hashApproval"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      calldataHash: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike,
      approvalDeadline: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashIntent"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      wallet: AddressLike,
      target: AddressLike,
      value: BigNumberish,
      calldataHash: BytesLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      policyHash: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextNonce"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "IntentExecuted"
  ): TypedContractEvent<
    IntentExecutedEvent.InputTuple,
    IntentExecutedEvent.OutputTuple,
    IntentExecutedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "IntentExecuted(address,address,address,uint256,bytes32)": TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;
    IntentExecuted: TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;
  };
}
