/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PolicyRegistry {
  export type AuthorizedCallStruct = {
    target: AddressLike;
    selector: BytesLike;
  };

  export type AuthorizedCallStructOutput = [
    target: string,
    selector: string
  ] & { target: string; selector: string };

  export type MandateStruct = {
    owner: AddressLike;
    agent: AddressLike;
    active: boolean;
    maxTxValue: BigNumberish;
    dailyLimit: BigNumberish;
    approvalThreshold: BigNumberish;
    validFrom: BigNumberish;
    validUntil: BigNumberish;
  };

  export type MandateStructOutput = [
    owner: string,
    agent: string,
    active: boolean,
    maxTxValue: bigint,
    dailyLimit: bigint,
    approvalThreshold: bigint,
    validFrom: bigint,
    validUntil: bigint
  ] & {
    owner: string;
    agent: string;
    active: boolean;
    maxTxValue: bigint;
    dailyLimit: bigint;
    approvalThreshold: bigint;
    validFrom: bigint;
    validUntil: bigint;
  };
}

export interface PolicyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentOf"
      | "authorizedCallKey"
      | "checkAuthorization"
      | "computePolicyId"
      | "createPolicy"
      | "getMandate"
      | "isCallAuthorized"
      | "isNativeTransferAuthorized"
      | "isPolicyActive"
      | "ownerOf"
      | "policyHashOf"
      | "policyIdOfHash"
      | "reactivatePolicy"
      | "resolvePolicyBinding"
      | "revokePolicy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallAuthorized"
      | "NativeTransferAuthorized"
      | "PolicyCreated"
      | "PolicyReactivated"
      | "PolicyRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agentOf", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "authorizedCallKey",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAuthorization",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "computePolicyId",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      PolicyRegistry.AuthorizedCallStruct[],
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getMandate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCallAuthorized",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNativeTransferAuthorized",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPolicyActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "ownerOf", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "policyHashOf",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "policyIdOfHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivatePolicy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolvePolicyBinding",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePolicy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "agentOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computePolicyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMandate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCallAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNativeTransferAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPolicyActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyHashOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyIdOfHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivatePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolvePolicyBinding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokePolicy",
    data: BytesLike
  ): Result;
}

export namespace CallAuthorizedEvent {
  export type InputTuple = [
    policyId: BytesLike,
    target: AddressLike,
    selector: BytesLike
  ];
  export type OutputTuple = [
    policyId: string,
    target: string,
    selector: string
  ];
  export interface OutputObject {
    policyId: string;
    target: string;
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeTransferAuthorizedEvent {
  export type InputTuple = [policyId: BytesLike, target: AddressLike];
  export type OutputTuple = [policyId: string, target: string];
  export interface OutputObject {
    policyId: string;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCreatedEvent {
  export type InputTuple = [
    policyId: BytesLike,
    owner: AddressLike,
    agent: AddressLike,
    salt: BytesLike,
    policyHash: BytesLike
  ];
  export type OutputTuple = [
    policyId: string,
    owner: string,
    agent: string,
    salt: string,
    policyHash: string
  ];
  export interface OutputObject {
    policyId: string;
    owner: string;
    agent: string;
    salt: string;
    policyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyReactivatedEvent {
  export type InputTuple = [policyId: BytesLike, owner: AddressLike];
  export type OutputTuple = [policyId: string, owner: string];
  export interface OutputObject {
    policyId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyRevokedEvent {
  export type InputTuple = [policyId: BytesLike, owner: AddressLike];
  export type OutputTuple = [policyId: string, owner: string];
  export interface OutputObject {
    policyId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyRegistry;
  waitForDeployment(): Promise<this>;

  interface: PolicyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentOf: TypedContractMethod<[policyId: BytesLike], [string], "view">;

  authorizedCallKey: TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [string],
    "view"
  >;

  checkAuthorization: TypedContractMethod<
    [
      policyHash: BytesLike,
      target: AddressLike,
      callKind: BigNumberish,
      selector: BytesLike,
      value: BigNumberish
    ],
    [
      [string, string, boolean, boolean, boolean, boolean] & {
        owner: string;
        agent: string;
        active: boolean;
        withinWindow: boolean;
        valueAllowed: boolean;
        callAllowed: boolean;
      }
    ],
    "view"
  >;

  computePolicyId: TypedContractMethod<
    [owner: AddressLike, salt: BytesLike],
    [string],
    "view"
  >;

  createPolicy: TypedContractMethod<
    [
      salt: BytesLike,
      agent: AddressLike,
      maxTxValue: BigNumberish,
      dailyLimit: BigNumberish,
      approvalThreshold: BigNumberish,
      validFrom: BigNumberish,
      validUntil: BigNumberish,
      calls: PolicyRegistry.AuthorizedCallStruct[],
      nativeTransferTargets: AddressLike[]
    ],
    [string],
    "nonpayable"
  >;

  getMandate: TypedContractMethod<
    [policyId: BytesLike],
    [PolicyRegistry.MandateStructOutput],
    "view"
  >;

  isCallAuthorized: TypedContractMethod<
    [policyId: BytesLike, target: AddressLike, selector: BytesLike],
    [boolean],
    "view"
  >;

  isNativeTransferAuthorized: TypedContractMethod<
    [policyId: BytesLike, target: AddressLike],
    [boolean],
    "view"
  >;

  isPolicyActive: TypedContractMethod<[policyId: BytesLike], [boolean], "view">;

  ownerOf: TypedContractMethod<[policyId: BytesLike], [string], "view">;

  policyHashOf: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  policyIdOfHash: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  reactivatePolicy: TypedContractMethod<
    [policyId: BytesLike],
    [void],
    "nonpayable"
  >;

  resolvePolicyBinding: TypedContractMethod<
    [policyHash: BytesLike],
    [[string, boolean] & { agent: string; active: boolean }],
    "view"
  >;

  revokePolicy: TypedContractMethod<
    [policyId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentOf"
  ): TypedContractMethod<[policyId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedCallKey"
  ): TypedContractMethod<
    [target: AddressLike, selector: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkAuthorization"
  ): TypedContractMethod<
    [
      policyHash: BytesLike,
      target: AddressLike,
      callKind: BigNumberish,
      selector: BytesLike,
      value: BigNumberish
    ],
    [
      [string, string, boolean, boolean, boolean, boolean] & {
        owner: string;
        agent: string;
        active: boolean;
        withinWindow: boolean;
        valueAllowed: boolean;
        callAllowed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "computePolicyId"
  ): TypedContractMethod<
    [owner: AddressLike, salt: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPolicy"
  ): TypedContractMethod<
    [
      salt: BytesLike,
      agent: AddressLike,
      maxTxValue: BigNumberish,
      dailyLimit: BigNumberish,
      approvalThreshold: BigNumberish,
      validFrom: BigNumberish,
      validUntil: BigNumberish,
      calls: PolicyRegistry.AuthorizedCallStruct[],
      nativeTransferTargets: AddressLike[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMandate"
  ): TypedContractMethod<
    [policyId: BytesLike],
    [PolicyRegistry.MandateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCallAuthorized"
  ): TypedContractMethod<
    [policyId: BytesLike, target: AddressLike, selector: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isNativeTransferAuthorized"
  ): TypedContractMethod<
    [policyId: BytesLike, target: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPolicyActive"
  ): TypedContractMethod<[policyId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[policyId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "policyHashOf"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "policyIdOfHash"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "reactivatePolicy"
  ): TypedContractMethod<[policyId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolvePolicyBinding"
  ): TypedContractMethod<
    [policyHash: BytesLike],
    [[string, boolean] & { agent: string; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokePolicy"
  ): TypedContractMethod<[policyId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "CallAuthorized"
  ): TypedContractEvent<
    CallAuthorizedEvent.InputTuple,
    CallAuthorizedEvent.OutputTuple,
    CallAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "NativeTransferAuthorized"
  ): TypedContractEvent<
    NativeTransferAuthorizedEvent.InputTuple,
    NativeTransferAuthorizedEvent.OutputTuple,
    NativeTransferAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCreated"
  ): TypedContractEvent<
    PolicyCreatedEvent.InputTuple,
    PolicyCreatedEvent.OutputTuple,
    PolicyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyReactivated"
  ): TypedContractEvent<
    PolicyReactivatedEvent.InputTuple,
    PolicyReactivatedEvent.OutputTuple,
    PolicyReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyRevoked"
  ): TypedContractEvent<
    PolicyRevokedEvent.InputTuple,
    PolicyRevokedEvent.OutputTuple,
    PolicyRevokedEvent.OutputObject
  >;

  filters: {
    "CallAuthorized(bytes32,address,bytes4)": TypedContractEvent<
      CallAuthorizedEvent.InputTuple,
      CallAuthorizedEvent.OutputTuple,
      CallAuthorizedEvent.OutputObject
    >;
    CallAuthorized: TypedContractEvent<
      CallAuthorizedEvent.InputTuple,
      CallAuthorizedEvent.OutputTuple,
      CallAuthorizedEvent.OutputObject
    >;

    "NativeTransferAuthorized(bytes32,address)": TypedContractEvent<
      NativeTransferAuthorizedEvent.InputTuple,
      NativeTransferAuthorizedEvent.OutputTuple,
      NativeTransferAuthorizedEvent.OutputObject
    >;
    NativeTransferAuthorized: TypedContractEvent<
      NativeTransferAuthorizedEvent.InputTuple,
      NativeTransferAuthorizedEvent.OutputTuple,
      NativeTransferAuthorizedEvent.OutputObject
    >;

    "PolicyCreated(bytes32,address,address,bytes32,bytes32)": TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
    PolicyCreated: TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;

    "PolicyReactivated(bytes32,address)": TypedContractEvent<
      PolicyReactivatedEvent.InputTuple,
      PolicyReactivatedEvent.OutputTuple,
      PolicyReactivatedEvent.OutputObject
    >;
    PolicyReactivated: TypedContractEvent<
      PolicyReactivatedEvent.InputTuple,
      PolicyReactivatedEvent.OutputTuple,
      PolicyReactivatedEvent.OutputObject
    >;

    "PolicyRevoked(bytes32,address)": TypedContractEvent<
      PolicyRevokedEvent.InputTuple,
      PolicyRevokedEvent.OutputTuple,
      PolicyRevokedEvent.OutputObject
    >;
    PolicyRevoked: TypedContractEvent<
      PolicyRevokedEvent.InputTuple,
      PolicyRevokedEvent.OutputTuple,
      PolicyRevokedEvent.OutputObject
    >;
  };
}
