/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPolicyRegistry {
  export type MandateStruct = {
    owner: AddressLike;
    agent: AddressLike;
    active: boolean;
    maxTxValue: BigNumberish;
    dailyLimit: BigNumberish;
    approvalThreshold: BigNumberish;
    validFrom: BigNumberish;
    validUntil: BigNumberish;
  };

  export type MandateStructOutput = [
    owner: string,
    agent: string,
    active: boolean,
    maxTxValue: bigint,
    dailyLimit: bigint,
    approvalThreshold: bigint,
    validFrom: bigint,
    validUntil: bigint
  ] & {
    owner: string;
    agent: string;
    active: boolean;
    maxTxValue: bigint;
    dailyLimit: bigint;
    approvalThreshold: bigint;
    validFrom: bigint;
    validUntil: bigint;
  };
}

export interface IPolicyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "checkAuthorization" | "getMandate" | "policyIdOfHash"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkAuthorization",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMandate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "policyIdOfHash",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMandate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyIdOfHash",
    data: BytesLike
  ): Result;
}

export interface IPolicyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPolicyRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPolicyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAuthorization: TypedContractMethod<
    [
      policyHash: BytesLike,
      target: AddressLike,
      callKind: BigNumberish,
      selector: BytesLike,
      value: BigNumberish
    ],
    [
      [string, string, boolean, boolean, boolean, boolean] & {
        owner: string;
        agent: string;
        active: boolean;
        withinWindow: boolean;
        valueAllowed: boolean;
        callAllowed: boolean;
      }
    ],
    "view"
  >;

  getMandate: TypedContractMethod<
    [policyId: BytesLike],
    [IPolicyRegistry.MandateStructOutput],
    "view"
  >;

  policyIdOfHash: TypedContractMethod<
    [policyHash: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAuthorization"
  ): TypedContractMethod<
    [
      policyHash: BytesLike,
      target: AddressLike,
      callKind: BigNumberish,
      selector: BytesLike,
      value: BigNumberish
    ],
    [
      [string, string, boolean, boolean, boolean, boolean] & {
        owner: string;
        agent: string;
        active: boolean;
        withinWindow: boolean;
        valueAllowed: boolean;
        callAllowed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMandate"
  ): TypedContractMethod<
    [policyId: BytesLike],
    [IPolicyRegistry.MandateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyIdOfHash"
  ): TypedContractMethod<[policyHash: BytesLike], [string], "view">;

  filters: {};
}
