/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  AlwaysRevertingTarget,
  AlwaysRevertingTargetInterface,
} from "../../../../contracts/mocks/TestTargets.sol/AlwaysRevertingTarget";

const _abi = [
  {
    inputs: [],
    name: "AlwaysReverts",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608080604052346013576061908160188239f35b5f80fdfe6080806040523615601c576040516311f9e53b60e21b8152600490fd5b6311f9e53b60e21b8152600490fdfea26469706673582212203240fdad1f3cccbad32afd31d489fc246cbe34900228c1fc88cc21b81790261864736f6c63430008180033";

type AlwaysRevertingTargetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AlwaysRevertingTargetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AlwaysRevertingTarget__factory extends ContractFactory {
  constructor(...args: AlwaysRevertingTargetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AlwaysRevertingTarget & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AlwaysRevertingTarget__factory {
    return super.connect(runner) as AlwaysRevertingTarget__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AlwaysRevertingTargetInterface {
    return new Interface(_abi) as AlwaysRevertingTargetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AlwaysRevertingTarget {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AlwaysRevertingTarget;
  }
}
