/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  SelectorTarget,
  SelectorTargetInterface,
} from "../../../../contracts/mocks/TestTargets.sol/SelectorTarget";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "value",
        type: "address",
      },
    ],
    name: "Bar",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Foo",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "bar",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "barCallCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "foo",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "fooCallCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100165761017c908161001b8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c80632fbebd38146100df5780633dfba05a146100c2578063646ea56d1461006557639ecfee2f14610045575f80fd5b34610061575f3660031901126100615760205f54604051908152f35b5f80fd5b34610061576020366003190112610061576004356001600160a01b0381160361006157610093600154610124565b6001557fc253aded44fe4151f1bd3a8ebd2736a3044cb408da5289395a1078e91d5072846020604051338152a1005b34610061575f366003190112610061576020600154604051908152f35b6020366003190112610061577f1176bd96090075e8a903f0c486668395688fc8c045fd7d1d173b9852e4613ca160206101185f54610124565b805f55604051908152a1005b5f1981146101325760010190565b634e487b7160e01b5f52601160045260245ffdfea264697066735822122072f64ab0d6199442ed8f721af7506fc59fca5dca20a4c1a50f38e73df12b36c164736f6c63430008180033";

type SelectorTargetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SelectorTargetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SelectorTarget__factory extends ContractFactory {
  constructor(...args: SelectorTargetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SelectorTarget & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SelectorTarget__factory {
    return super.connect(runner) as SelectorTarget__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SelectorTargetInterface {
    return new Interface(_abi) as SelectorTargetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SelectorTarget {
    return new Contract(address, _abi, runner) as unknown as SelectorTarget;
  }
}
