/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyRegistry,
  IPolicyRegistryInterface,
} from "../../../contracts/interfaces/IPolicyRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "policyHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "enum IPolicyRegistry.CallKind",
        name: "callKind",
        type: "uint8",
      },
      {
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "checkAuthorization",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "withinWindow",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "valueAllowed",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "callAllowed",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "policyId",
        type: "bytes32",
      },
    ],
    name: "getMandate",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "agent",
            type: "address",
          },
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "uint128",
            name: "maxTxValue",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "dailyLimit",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "approvalThreshold",
            type: "uint128",
          },
          {
            internalType: "uint64",
            name: "validFrom",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "validUntil",
            type: "uint64",
          },
        ],
        internalType: "struct IPolicyRegistry.Mandate",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "policyHash",
        type: "bytes32",
      },
    ],
    name: "policyIdOfHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPolicyRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyRegistryInterface {
    return new Interface(_abi) as IPolicyRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyRegistry {
    return new Contract(address, _abi, runner) as unknown as IPolicyRegistry;
  }
}
