/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SelectorTargetInterface extends Interface {
  getFunction(
    nameOrSignature: "bar" | "barCallCount" | "foo" | "fooCallCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Bar" | "Foo"): EventFragment;

  encodeFunctionData(functionFragment: "bar", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "barCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "foo", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fooCallCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "bar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "barCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "foo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fooCallCount",
    data: BytesLike
  ): Result;
}

export namespace BarEvent {
  export type InputTuple = [value: AddressLike];
  export type OutputTuple = [value: string];
  export interface OutputObject {
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FooEvent {
  export type InputTuple = [value: BigNumberish];
  export type OutputTuple = [value: bigint];
  export interface OutputObject {
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SelectorTarget extends BaseContract {
  connect(runner?: ContractRunner | null): SelectorTarget;
  waitForDeployment(): Promise<this>;

  interface: SelectorTargetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bar: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  barCallCount: TypedContractMethod<[], [bigint], "view">;

  foo: TypedContractMethod<[arg0: BigNumberish], [void], "payable">;

  fooCallCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bar"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "barCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "foo"
  ): TypedContractMethod<[arg0: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "fooCallCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Bar"
  ): TypedContractEvent<
    BarEvent.InputTuple,
    BarEvent.OutputTuple,
    BarEvent.OutputObject
  >;
  getEvent(
    key: "Foo"
  ): TypedContractEvent<
    FooEvent.InputTuple,
    FooEvent.OutputTuple,
    FooEvent.OutputObject
  >;

  filters: {
    "Bar(address)": TypedContractEvent<
      BarEvent.InputTuple,
      BarEvent.OutputTuple,
      BarEvent.OutputObject
    >;
    Bar: TypedContractEvent<
      BarEvent.InputTuple,
      BarEvent.OutputTuple,
      BarEvent.OutputObject
    >;

    "Foo(uint256)": TypedContractEvent<
      FooEvent.InputTuple,
      FooEvent.OutputTuple,
      FooEvent.OutputObject
    >;
    Foo: TypedContractEvent<
      FooEvent.InputTuple,
      FooEvent.OutputTuple,
      FooEvent.OutputObject
    >;
  };
}
