/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockAgentRegistry,
  MockAgentRegistryInterface,
} from "../../../contracts/mocks/MockAgentRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "isActiveAgent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "bool",
        name: "active_",
        type: "bool",
      },
    ],
    name: "setActive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner_",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576101c7908161001b8239f35b5f80fdfe60806040908082526004361015610014575f80fd5b5f3560e01c90816314afd79e1461014457508063299a7bcc146100f55780632ce962cf14610088576365e1e4661461004a575f80fd5b34610084576020366003190112610084576020906001600160a01b0361006e61017b565b165f525f825260ff815f20541690519015158152f35b5f80fd5b50346100845780600319360112610084576100a161017b565b90602435908115158092036100845760018060a01b0380931691825f525f602052815f209060ff8019835416911617905560016020525f20918254908116156100e657005b6001600160a01b031916179055005b503461008457806003193601126100845761010e61017b565b6001600160a01b0360243581811693929084900361008457165f90815260016020522080546001600160a01b0319169091179055005b905034610084576020366003190112610084576020916001600160a01b03908161016c61017b565b165f52600184525f2054168152f35b600435906001600160a01b03821682036100845756fea2646970667358221220fbc3aa7a2465484948397a98677487f5db11f7b1237d43560490cf78583f6c2c64736f6c63430008180033";

type MockAgentRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAgentRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAgentRegistry__factory extends ContractFactory {
  constructor(...args: MockAgentRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockAgentRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockAgentRegistry__factory {
    return super.connect(runner) as MockAgentRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAgentRegistryInterface {
    return new Interface(_abi) as MockAgentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockAgentRegistry {
    return new Contract(address, _abi, runner) as unknown as MockAgentRegistry;
  }
}
