/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPolicyRegistry {
  export type MandateStruct = {
    owner: AddressLike;
    agent: AddressLike;
    active: boolean;
    maxTxValue: BigNumberish;
    dailyLimit: BigNumberish;
    approvalThreshold: BigNumberish;
    validFrom: BigNumberish;
    validUntil: BigNumberish;
  };

  export type MandateStructOutput = [
    owner: string,
    agent: string,
    active: boolean,
    maxTxValue: bigint,
    dailyLimit: bigint,
    approvalThreshold: bigint,
    validFrom: bigint,
    validUntil: bigint
  ] & {
    owner: string;
    agent: string;
    active: boolean;
    maxTxValue: bigint;
    dailyLimit: bigint;
    approvalThreshold: bigint;
    validFrom: bigint;
    validUntil: bigint;
  };
}

export interface MockPolicyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeCall"
      | "authorizeNativeTransfer"
      | "checkAuthorization"
      | "getMandate"
      | "policyIdOfHash"
      | "setBinding"
      | "setFullBinding"
      | "setSpendingPolicy"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "authorizeCall",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeNativeTransfer",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAuthorization",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMandate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "policyIdOfHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBinding",
    values: [BytesLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFullBinding",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      boolean,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setSpendingPolicy",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeNativeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMandate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyIdOfHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBinding", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFullBinding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSpendingPolicy",
    data: BytesLike
  ): Result;
}

export interface MockPolicyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MockPolicyRegistry;
  waitForDeployment(): Promise<this>;

  interface: MockPolicyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeCall: TypedContractMethod<
    [policyHash: BytesLike, target: AddressLike, selector: BytesLike],
    [void],
    "nonpayable"
  >;

  authorizeNativeTransfer: TypedContractMethod<
    [policyHash: BytesLike, target: AddressLike],
    [void],
    "nonpayable"
  >;

  checkAuthorization: TypedContractMethod<
    [
      policyHash: BytesLike,
      target: AddressLike,
      callKind: BigNumberish,
      selector: BytesLike,
      value: BigNumberish
    ],
    [
      [string, string, boolean, boolean, boolean, boolean] & {
        owner: string;
        agent: string;
        active: boolean;
        withinWindow: boolean;
        valueAllowed: boolean;
        callAllowed: boolean;
      }
    ],
    "view"
  >;

  getMandate: TypedContractMethod<
    [policyId: BytesLike],
    [IPolicyRegistry.MandateStructOutput],
    "view"
  >;

  policyIdOfHash: TypedContractMethod<
    [policyHash: BytesLike],
    [string],
    "view"
  >;

  setBinding: TypedContractMethod<
    [policyHash: BytesLike, agent: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  setFullBinding: TypedContractMethod<
    [
      policyHash: BytesLike,
      owner: AddressLike,
      agent: AddressLike,
      active: boolean,
      withinWindow: boolean,
      maxTxValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setSpendingPolicy: TypedContractMethod<
    [
      policyHash: BytesLike,
      dailyLimit: BigNumberish,
      approvalThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeCall"
  ): TypedContractMethod<
    [policyHash: BytesLike, target: AddressLike, selector: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeNativeTransfer"
  ): TypedContractMethod<
    [policyHash: BytesLike, target: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkAuthorization"
  ): TypedContractMethod<
    [
      policyHash: BytesLike,
      target: AddressLike,
      callKind: BigNumberish,
      selector: BytesLike,
      value: BigNumberish
    ],
    [
      [string, string, boolean, boolean, boolean, boolean] & {
        owner: string;
        agent: string;
        active: boolean;
        withinWindow: boolean;
        valueAllowed: boolean;
        callAllowed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMandate"
  ): TypedContractMethod<
    [policyId: BytesLike],
    [IPolicyRegistry.MandateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyIdOfHash"
  ): TypedContractMethod<[policyHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setBinding"
  ): TypedContractMethod<
    [policyHash: BytesLike, agent: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFullBinding"
  ): TypedContractMethod<
    [
      policyHash: BytesLike,
      owner: AddressLike,
      agent: AddressLike,
      active: boolean,
      withinWindow: boolean,
      maxTxValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSpendingPolicy"
  ): TypedContractMethod<
    [
      policyHash: BytesLike,
      dailyLimit: BigNumberish,
      approvalThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
