/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ReentrantAttackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "guard"
      | "reentered"
      | "reentryCalldata"
      | "reentryReturnData"
      | "reentrySucceeded"
      | "setGuard"
      | "setReentryCalldata"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "guard", values?: undefined): string;
  encodeFunctionData(functionFragment: "reentered", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reentryCalldata",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentryReturnData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentrySucceeded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGuard",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReentryCalldata",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "guard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reentered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reentryCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentryReturnData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentrySucceeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReentryCalldata",
    data: BytesLike
  ): Result;
}

export interface ReentrantAttacker extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrantAttacker;
  waitForDeployment(): Promise<this>;

  interface: ReentrantAttackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  guard: TypedContractMethod<[], [string], "view">;

  reentered: TypedContractMethod<[], [boolean], "view">;

  reentryCalldata: TypedContractMethod<[], [string], "view">;

  reentryReturnData: TypedContractMethod<[], [string], "view">;

  reentrySucceeded: TypedContractMethod<[], [boolean], "view">;

  setGuard: TypedContractMethod<[guard_: AddressLike], [void], "nonpayable">;

  setReentryCalldata: TypedContractMethod<
    [data: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "guard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reentered"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "reentryCalldata"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reentryReturnData"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reentrySucceeded"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setGuard"
  ): TypedContractMethod<[guard_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReentryCalldata"
  ): TypedContractMethod<[data: BytesLike], [void], "nonpayable">;

  filters: {};
}
